### ISSUE TITLE
Adding Malayalam

### ISSUE THREAD

**Issue by EnjoyerofChrist** [lemuelinchrist/hymnsforandroid#3]
Could there be a version with the Malayalam language added to the bottom (under Farsi)? I realize there is a version with English and Malayalam only, but I use other languages as well, such as Spanish, Chinese, German, and Korean. So many saints, including myself, are grateful to the Lord for your service!

The version with Malayalam and English can be found here:
https://drive.google.com/file/d/1MdbGkxoqBRC5WsMdgqff8Xg6gAcDTFBN/view

-Samuel

**Comment by lemuelinchrist** [comment]
Hi Brother, the Malayalam version is forked by a separate group of brothers and I do not have their code at hand. After fellowship, It was their desire to keep the Malayalam language in a separate app for various reasons. Please reach out to them if you need the two projects merged. Thank you
